name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x, 16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build
            - name: linux package
              uses: actions/upload-artifact@v2.2.4
              with:
                  name: app
                  path: index-linux
            - name: mac package
              uses: actions/upload-artifact@v2.2.4
              with:
                  name: app
                  path: index-macos
            - name: win package
              uses: actions/upload-artifact@v2.2.4
              with:
                  name: app
                  path: index-win.exe
